# Generated by Django 5.0.3 on 2024-03-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clientName", models.CharField(max_length=100)),
                ("clientEmail", models.EmailField(max_length=100)),
                ("clientMessage", models.CharField(max_length=255)),
            ],
        ),
    ]
